/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: tori1243 (https://sketchfab.com/tori1243)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/excavator-animation-940258497f9f4eba9710bb359a9e777e
title: Excavator Animation
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/modeexcavator.gltf");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.5}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            name="Tread_GEO"
            position={[0.48, -6.21, -21.03]}
            rotation={[0, -0.02, 0]}
          >
            <group
              position={[-0.11, 1.22, 1.83]}
              rotation={[-Math.PI, -0.13, -Math.PI]}
            >
              <group position={[1.01, 1.29, -3.73]} rotation={[0.03, 0, 0]}>
                <group position={[0.14, 8.33, -13.51]} rotation={[0.05, 0, 0]}>
                  <group
                    position={[-0.31, -7.89, -2.43]}
                    rotation={[0.25, 0, 0]}
                  >
                    <mesh
                      geometry={nodes.claw_GEO_Scoop_MAT_0.geometry}
                      material={nodes.claw_GEO_Scoop_MAT_0.material}
                    />
                    <mesh
                      geometry={nodes.claw_GEO_Bolts_MAT_0.geometry}
                      material={nodes.claw_GEO_Bolts_MAT_0.material}
                    />
                  </group>
                  <group position={[-0.34, -8.38, -2.19]}>
                    <mesh
                      geometry={nodes.shovel_GEO_Bolts_MAT_0.geometry}
                      material={nodes.shovel_GEO_Bolts_MAT_0.material}
                    />
                    <mesh
                      geometry={nodes.shovel_GEO_Scoop_MAT_0.geometry}
                      material={nodes.shovel_GEO_Scoop_MAT_0.material}
                    />
                    <mesh
                      geometry={nodes.shovel_GEO_Rod_MAT_0.geometry}
                      material={nodes.shovel_GEO_Rod_MAT_0.material}
                    />
                  </group>
                  <mesh
                    geometry={nodes.Arm_2_GEO_Arm_MAT_0.geometry}
                    material={nodes.Arm_2_GEO_Arm_MAT_0.material}
                  />
                  <mesh
                    geometry={nodes.Arm_2_GEO_Bolts_MAT_0.geometry}
                    material={nodes.Arm_2_GEO_Bolts_MAT_0.material}
                  />
                  <mesh
                    geometry={nodes.Arm_2_GEO_Pipe_MAT_0.geometry}
                    material={nodes.Arm_2_GEO_Pipe_MAT_0.material}
                  />
                </group>
                <mesh
                  geometry={nodes.arm_01_GEO1_Arm_MAT_0.geometry}
                  material={nodes.arm_01_GEO1_Arm_MAT_0.material}
                />
                <mesh
                  geometry={nodes.arm_01_GEO1_Pipe_MAT_0.geometry}
                  material={nodes.arm_01_GEO1_Pipe_MAT_0.material}
                />
                <mesh
                  geometry={nodes.arm_01_GEO1_Bolts_MAT_0.geometry}
                  material={nodes.arm_01_GEO1_Bolts_MAT_0.material}
                />
              </group>
              <mesh
                geometry={nodes.Body_GEO_Arm_MAT_0.geometry}
                material={nodes.Body_GEO_Arm_MAT_0.material}
              />
              <mesh
                geometry={nodes.Body_GEO_Body_MAT_0.geometry}
                material={nodes.Body_GEO_Body_MAT_0.material}
              />
              <mesh
                geometry={nodes.Body_GEO_Rod_MAT_0.geometry}
                material={nodes.Body_GEO_Rod_MAT_0.material}
              />
              <mesh
                geometry={nodes.Body_GEO_phong3_0.geometry}
                material={materials.phong3}
              />
              <mesh
                geometry={nodes.Body_GEO_Chair_MAT_0.geometry}
                material={materials.Chair_MAT}
              />
              <mesh
                geometry={nodes.Body_GEO_Pedal_MAT_0.geometry}
                material={materials.Pedal_MAT}
              />
              <mesh
                geometry={nodes.Body_GEO_Control_MAT_0.geometry}
                material={materials.Control_MAT}
              />
            </group>
            <mesh
              geometry={nodes.Tread_GEO_Body_MAT_0.geometry}
              material={nodes.Tread_GEO_Body_MAT_0.material}
            />
            <mesh
              geometry={nodes.Tread_GEO_Gear_MAT_0.geometry}
              material={materials.Gear_MAT}
            />
            <mesh
              geometry={nodes.Tread_GEO_Rod_MAT_0.geometry}
              material={nodes.Tread_GEO_Rod_MAT_0.material}
            />
            <mesh
              geometry={nodes.Tread_GEO_Tire_MAT_0.geometry}
              material={materials.Tire_MAT}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/modeexcavator.gltf");
